### ISSUE TITLE
Add code lint?

### ISSUE THREAD

**Issue by ChurchTao** [ChurchTao/Lanaya#10]
@robertrosman 
I don't know how to add code lint or format to project. Like `prettier`.
This keeps our code style consistent and avoids conflicts caused by formatting.
Would you help me do this.

**Comment by ChurchTao** [comment]
In fact, I am a back-end programmer, and I don’t know much about plug-ins like eslint.
😄

**Comment by robertrosman** [comment]
Sure I can have a look, it's usually pretty straight forward 👍

**Comment by ChurchTao** [comment]
> Sure I can have a look, it's usually pretty straight forward 👍

So great, I resolve some error of lint and `pr.yml`, it works.
