### ISSUE TITLE
关于 macos 自动粘贴的功能

### ISSUE THREAD

**Issue by ayangweb** [ChurchTao/Lanaya#13]
大佬，您好，我也正在做一款剪切板 app：[EcoPaste](https://github.com/ayangweb/EcoPaste)，通过查看您的项目源码受益匪浅！非常感谢！

不过我在 MacOS 使用自动粘贴的时候遇到了一个问题，因为我的 app 是有 pin 功能，可以固定在屏幕上！

<img width="390" alt="image" src="https://github.com/user-attachments/assets/a34eeb94-f77e-45ef-b875-78f20f949d63">

举例：如果我是打开 QQ 之后打开的 EcoPaste，然后我 pin 住了 EcoPaste，然后从 QQ 切换到微信，自动粘贴的时候会聚焦 QQ 而不是微信！这个问题就是由于我在显示窗口的时候获取了 QQ 的进程 id，自动粘贴也是通过 QQ 进程 id 来实现上一个窗口聚焦，您知道这个问题我应该如何优雅的去处理吗？我查询了 chatgpt n 次，都没有给我一个合适的解决方案！

**Comment by ayangweb** [comment]
https://github.com/ayangweb/EcoPaste/pull/233 已实现，现在就得研究同样思路下的 windows 代码咋实现，有个固定窗口的功能就有很多的麻烦需要处理！

**Comment by ChurchTao** [comment]
这个项目好久没维护了，没看见，sorry 😄

**Comment by ayangweb** [comment]
> 这个项目好久没维护了，没看见，sorry 😄

哈哈，还是大佬你之前给我的 https://github.com/ChurchTao/clipboard-rs/issues/26#issuecomment-2174849575 这个思路！
